name: binarization
channels:
  - https://conda.binstar.org/menpo
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.7.1
  - astor=0.7.1
  - backports=1.0
  - backports.weakref=1.0.post1
  - c-ares=1.15.0
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - enum34=1.1.6
  - funcsigs=1.0.2
  - futures=3.3.0
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - keras=2.2.2
  - keras-applications=1.0.4
  - keras-preprocessing=1.0.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx
  - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - libgpuarray=0.7.6
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libprotobuf=3.9.0
  - linecache2=1.0.0
  - mako=1.0.10
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mock=3.0.5
  - ncurses=6.1
  - numpy=1.16.4
  - openblas=0.3.6
  - opencv=2.4.11
  - openssl=1.1.1c
  - pip=19.1.1
  - protobuf=3.9.0
  - pygpu=0.7.6
  - python=2.7.16
  - pyyaml=5.1.1
  - readline=7.0
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tbb
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - termcolor=1.1.0
  - theano=1.0.3
  - tk=8.6.8
  - traceback2=1.4.0
  - unittest2=1.1.0
  - werkzeug=0.15.5
  - wheel=0.33.4
  - yaml=0.1.7
  - zlib=1.2.11
#prefix: /Users/mike/anaconda3/envs/binarization

